### ISSUE TITLE
Create an exchange guide for IOTA EVM

### ISSUE THREAD

**Issue by lucas-tortora** [iotaledger/devx#319]

**Comment by jlvandenhout** [comment]
- I started a discussion about what should be included. Mark and Mido should be in the proces of finding out what Bitfinex would require, as a guidance.
- Summarized what I think should be in there here: https://iotafoundation.slack.com/archives/C06KY8SSGS0/p1708684230224899?thread_ts=1708506837.033189&cid=C06KY8SSGS0
- Since IOTA EVM and Shimmer EVM are standard Ethereum JSON RPC, I think the focus should be on setting up Hornet and Wasp, tools and endpoints to manage them, and any specifics where we differ from Ethereum, although I'm not sure how many practical differences are left.
