### ISSUE TITLE
Add resource requirement for WASP node

### ISSUE THREAD

**Issue by trungtt198x** [iotaledger/devx#347]
Please mention the minimum resource requirement for installing/deploying own WASP node:

8CPU + 16GB RAM, 250GB disk

Maybe, we can place it here?
https://wiki.iota.org/hornet/how_tos/using_docker

**Comment by Dr-Electron** [comment]
I would add it to the wasp docs. But anyway, 8CPU? Are these the minimum or recommended requirements? Because I run wasp fine on my 4CPU server. Obviously this will depend a lot on the amount of API requests, but that should be handled by a load balancer anyway I guess 🤔 
So can we change it to recommended requirements? Did you get this info from DevOps?

**Comment by trungtt198x** [comment]
> I would add it to the wasp docs. But anyway, 8CPU? Are these the minimum or recommended requirements? Because I run wasp fine on my 4CPU server. Obviously this will depend a lot on the amount of API requests, but that should be handled by a load balancer anyway I guess 🤔 So can we change it to recommended requirements? Did you get this info from DevOps?

sure things, I've got that min from Thomas
